# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
        ('course', '0002_auto_20171028_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsubmit',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Test'),
        ),
        migrations.AddField(
            model_name='testsubmit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Test'),
        ),
        migrations.AddField(
            model_name='homeworksubmit',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Homework'),
        ),
        migrations.AddField(
            model_name='homeworksubmit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Chapter'),
        ),
    ]
