# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20171015_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='homeworksubmit',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
