# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0002_auto_20170302_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('question', jsonfield.fields.JSONField(default=dict)),
                ('answer', jsonfield.fields.JSONField(default=dict)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='problem_file',
        ),
        migrations.RemoveField(
            model_name='homeworksubmit',
            name='submit_file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.AddField(
            model_name='homework',
            name='problems',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='homeworksubmit',
            name='submit_content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='problem',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='submit',
            field=models.TextField(),
        ),
    ]
