# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170222_1724'),
        ('material', '0002_auto_20170223_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsubmit',
            old_name='submit_user_id',
            new_name='submit_user',
        ),
        migrations.RenameField(
            model_name='testsubmit',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='problem_file',
        ),
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.Unit'),
        ),
    ]
