# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_unit_lists'),
        ('material', '0002_auto_20171028_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Unit'),
        ),
    ]
