# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 15:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20170604_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='problems',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='test',
            name='problem',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
