# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_test_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(help_text='链接'),
        ),
    ]
