# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(6, '用户名至少%(value)位!'), django.core.validators.MaxLengthValidator(16, '用户名至多%(value)位!')])),
                ('password', models.TextField(validators=[django.core.validators.MaxLengthValidator(20, '密码至多%(value)位!'), django.core.validators.MinLengthValidator(6, '密码至少%(value)位!')])),
                ('mail', models.TextField(blank=True)),
                ('role', models.IntegerField(choices=[(0, 'Administrator'), (1, 'Teacher'), (2, 'Student')], default=2)),
                ('nickname', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(26, '昵称至多%(value)位!'), django.core.validators.MinLengthValidator(4, '昵称至少%(value)位!')])),
            ],
        ),
    ]
