# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(26, '昵称至多%(value)位!'), django.core.validators.MinLengthValidator(4, '昵称至少%(value)位!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(20, '密码至多%(value)位!'), django.core.validators.MinLengthValidator(6, '密码至少%(value)位!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(6, '用户名至少%(value)位!'), django.core.validators.MaxLengthValidator(16, '用户名至多%(value)位!')]),
        ),
    ]
