# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 12:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170201_2013'),
        ('homework', '0002_auto_20170201_2013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0002_auto_20170201_2013'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(26, '昵称至多%(value)位!'), django.core.validators.MinLengthValidator(4, '昵称至少%(value)位!')])),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
