# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 13:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170205_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(26, '昵称至多%(limit_value)s位!'), django.core.validators.MinLengthValidator(4, '昵称至少%(limit_value)s位!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(6, '密码至少%(limit_value)s位!'), django.core.validators.MaxLengthValidator(120, '密码至多%(limit_value)s位!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(6, '用户名至少%(limit_value)s位!'), django.core.validators.MaxLengthValidator(16, '用户名至多%(limit_value)s位!')]),
        ),
    ]
