# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_assistant_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assistant_course',
        ),
    ]
