# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 12:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_auto_20170201_2013'),
        ('user', '0002_auto_20170201_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MaxLengthValidator(20, '板块名字不能多于%(value)位!'), django.core.validators.MinLengthValidator(6, '板块名字不能少于%(value)位')])),
                ('posts_length', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(50, '标题字数不能多于%(value)位!'), django.core.validators.MinLengthValidator(6, '标题字数不能少于%(value)位')])),
                ('content', models.TextField(error_messages={'blank': '帖子内容不能为空!'})),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Forum')),
                ('parent', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='bbs.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account')),
            ],
        ),
    ]
