# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MaxLengthValidator(20, '板块名字不能多于%(limit_value)s位!'), django.core.validators.MinLengthValidator(3, '板块名字不能少于%(limit_value)s位')])),
                ('posts_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(50, '标题字数不能多于%(limit_value)s位!'), django.core.validators.MinLengthValidator(6, '标题字数不能少于%(limit_value)s位')])),
                ('content', models.TextField(error_messages={'blank': '帖子内容不能为空!'})),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Forum')),
            ],
        ),
    ]
