# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(validators=[django.core.validators.MaxLengthValidator(50, '标题字数不能多于%(value)位!'), django.core.validators.MinLengthValidator(6, '标题字数不能多于%(value)位')])),
                ('content', models.TextField(error_messages={'blank': '帖子内容不能为空!'})),
                ('course', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('parent', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='session.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
