// Session
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'

// User
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'


// BBS
export const FORUM_FETCH_SUCCESS = 'FORUM_FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS'

// Course
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST'
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'

// Course Chapter
export const GET_CHAPTER_REQUEST = 'GET_CHAPTER_REQUEST'
export const GET_CHAPTER_FAILED = 'GET_CHAPTER_FAILED'
export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS'

export const GET_CHAPTERS_REQUEST = 'GET_CHAPTER_REQUEST'
export const GET_CHAPTERS_FAILED = 'GET_CHAPTER_FAILED'
export const GET_CHAPTERS_SUCCESS = 'GET_CHAPTER_SUCCESS'

// Course Chapter Unit
export const GET_UNITS_REQUEST = 'GET_UNITS_REQUEST'
export const GET_UNITS_FAILED = 'GET_UNITS_FAILED'
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS'

export const GET_UNIT_REQUEST = 'GET_UNIT_REQUEST'
export const GET_UNIT_FAILED = 'GET_UNIT_FAILED'
export const GET_UNIT_SUCCESS = 'GET_UNIT_SUCCESS'

export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST'
export const GET_VIDEOS_FAILED = 'GET_VIDEOS_FAILED'
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS'


// material
export const GET_HOMEWORK_REQUEST = 'GET_HOMEWORK_REQUEST'
export const GET_HOMEWORK_FAILED = 'GET_HOMEWORK_FAILED'
export const GET_HOMEWORK_SUCCESS = 'GET_HOMEWORK_SUCCESS'

export const GET_HOMEWORK_SUBMIT_REQUEST = 'GET_HOMEWORK_SUBMIT_REQUEST'
export const GET_HOMEWORK_SUBMIT_FAILED = 'GET_HOMEWORK_SUBMIT_FAILED'
export const GET_HOMEWORK_SUBMIT_SUCCESS = 'GET_HOMEWORK_SUBMIT_SUCCESS'

export const POST_HOMEWORK_REQUEST = 'POST_HOMEWORK_REQUEST'
export const POST_HOMEWORK_FAILED = 'POST_HOMEWORK_FAILED'
export const POST_HOMEWORK_SUCCESS = 'POST_HOMEWORK_SUCCESS'

export const GET_VIDEO_REQUEST = 'GET_VIDEO_REQUEST'
export const GET_VIDEO_FAILED = 'GET_VIDEO_FAILED'
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS'
