# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmit',
            name='judge_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_judge_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeworksubmit',
            name='submit_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submit_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsubmit',
            name='submit_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submit_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
