# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', jsonfield.fields.JSONField(default=list, help_text='单元')),
                ('title', models.TextField(help_text='标题')),
                ('description', models.TextField(help_text='说明')),
                ('materials', jsonfield.fields.JSONField(default=list, help_text='课程资料')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='标题')),
                ('subtitle', models.TextField(help_text='副标题')),
                ('introduction', models.TextField(help_text='内容介绍')),
                ('cover_image', models.ImageField(help_text='封面图', upload_to='')),
                ('sections', jsonfield.fields.JSONField(default=list, help_text='章')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('participants_count', models.IntegerField(default=0, help_text='参与人数')),
            ],
        ),
        migrations.CreateModel(
            name='CourseParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, help_text='是否完成')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.IntegerField(default=0, help_text='作业与测试的总分')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='标题')),
                ('description', models.TextField(help_text='说明')),
                ('lists', jsonfield.fields.JSONField(default=list, help_text='内容')),
            ],
        ),
    ]
