# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:50
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
class Migration(migrations.Migration):
    dependencies = [
        ('course', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='materials',
            field=jsonfield.fields.JSONField(default=list, help_text='课程资料'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='units',
            field=jsonfield.fields.JSONField(default=list, help_text='单元'),
        ),
        migrations.AlterField(
            model_name='course',
            name='obligator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=jsonfield.fields.JSONField(default=list, help_text='章'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lists',
            field=jsonfield.fields.JSONField(default=list, help_text='内容'),
        ),
    ]