# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170302_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.TextField(help_text='封面图'),
        ),
    ]
