# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20171006_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
