# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170220_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
