# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_course_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='leacturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='obligator',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='leacturer',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Chapter'),
            preserve_default=False,
        ),
    ]
