# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20171022_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='units',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
    ]
